# Generated by Django 6.0 on 2026-01-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_address_userprofile_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/normal.jpg', null=True, upload_to='avatars/'),
        ),
    ]
