# Generated by Django 6.0 on 2026-01-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_nationality_userprofile_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_image',
        ),
    ]
