# Generated by Django 6.0 on 2026-01-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_banned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_unactivate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
