# Generated by Django 6.0 on 2026-01-09 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_cover_image'),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='accounts.user'),
        ),
    ]
