# Generated by Django 5.2.10 on 2026-01-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb_text', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verb_code', models.CharField(choices=[('like_post', 'Like Post'), ('comment_post', 'Comment Post'), ('reply_comment', 'Reply Comment'), ('mention_post', 'Mention Post'), ('mention_comment', 'Mention Comment'), ('share_post', 'Share Post'), ('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accept')], max_length=50)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='accounts.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.user')),
            ],
        ),
    ]
